#!/usr/bin/env bash

# Update and upgrade beforehand
brew update
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Install Bash 4
brew install bash

# Install wget with IRI support
brew install wget

# Install other useful binaries
brew install aspell \
  bat \
  direnv \
  djvu2pdf \
  fd \
  fzf \
  git \
  gnupg \
  gnupg2 \
  gnutls \
  html2text \
  icu4c \
  jq \
  keychain \
  k9s \
  lazygit \
  less \
  libidn \
  lynx \
  msmtp \
  nodejs \
  nvim \
  pigz \
  pinentry-mac \
  psutils \
  python3 \
  reattach-to-user-namespace \
  ripgrep \
  stow \
  unixodbc \
  urlview \
  vim \
  zlib \
  zsh \
  zsh-completions \
  zsh-syntax-highlighting

# Install favorite fonts
brew install --cask font-fira-code
brew install --cask font-meslo-lg-nerd-font

# Install development tools
brew install poetry
brew install pyenv
brew install --cask docker
brew install terraform
# This is needed for emacs
brew tap railwaycat/emacsmacport
brew install emacs-mac --with-modules --with-starter

# General mac stuff
# Window management
brew install --cask amethyst
# Nice monitoring in the menu bar
brew install --cask menumeters
# A browser would be nice, too.
brew install --cask brave-browser

# Remove outdated versions from the cellar
brew cleanup
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
