#!/usr/bin/env bash

# Update and upgrade beforehand
brew update
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Install Bash 4
brew install bash

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew tap homebrew/dupes
brew install homebrew/dupes/grep

# Install other useful binaries
brew install ack
brew install aspell
brew install contacts
brew install djvu2pdf
brew install emacs
brew install git
brew install gnupg
brew install gnupg2
brew install gnutls
brew install html2text
brew install icu4c
brew install keychain
brew install libidn
brew install lynx
brew install msmtp
brew install mu
brew install mutt --with-sidebar-patch
brew install mysql
brew install offline-imap
brew install pass
brew install pigz
brew install pinentry-mac
brew install psutils
brew install python3
brew install reattach-to-user-namespace
brew install stow
brew install the_silver_searcher
brew install tmux
brew install transmission
brew install unixodbc
brew install urlview
brew install vim
brew install vimpager
brew install zlib
brew install zsh
brew install zsh-completions
brew install zsh-syntax-highlighting

brew tap homebrew/versions
brew install lua52

# Install native apps
brew tap phinze/homebrew-cask
brew install brew-cask

function installcask() {
    brew cask install "${@}" 2> /dev/null
}

installcask alfred
installcask calibre
installcask google-chrome
installcask iterm2
installcask keyremap4macbook
installcask macvim
installcask sequel-pro
installcask skim
installcask the-unarchiver
installcask ukelele
installcask vlc

# Allow alfred to find cask apps
brew cask alfred link

# Remove outdated versions from the cellar
brew cleanup
