repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.2
    hooks:
      - id: markdownlint-cli2
        files: ^README\.md$
  - repo: local
    hooks:
      - id: nil
        name: nil diagnostics
        entry: nil diagnostics --deny-warnings
        language: system
        files: \.nix$
      - id: statix
        name: statix check
        entry: statix check
        language: system
        files: \.nix$
        pass_filenames: false
