" vim: foldmethod=marker fenc=utf-8 tw=80 sw=2 sts=2 :
scriptencoding utf-8
set nocompatible        " Use Vim defaults (much better!)
" Plugins are managed by nix (home/vim.nix), not vim-plug
" General configuration {{{1
filetype plugin indent on
set shell=/bin/bash
set laststatus=2
set encoding=utf-8
set backspace=indent,eol,start       " Allow backspacing over everything in
                                     " insert mode
set ai                               " Always set auto-indenting on
set history=50                       " keep 50 lines of command history
set ruler                            " Show the cursor position all the time
set relativenumber
set number
set clipboard=unnamed
set showmatch
set incsearch
syntax on
set showcmd
set wildmenu
set viminfo='20,\"500   " Keep a .viminfo file.
set guifont=Fira\ Code:h20
set expandtab
set shiftwidth=4
set tabstop=4
set smarttab
set shiftround
set textwidth=0
set hidden
let g:netrw_liststyle=3
set omnifunc=syntaxcomplete#Complete
set grepprg=grep\ -nH\ $*
let g:tex_flavor='latex'
augroup texAngleConceal
  autocmd!
  au BufNewFile,BufRead *.tex syn match texMathSymbol '\\langle\>' contained conceal cchar=⟨
  au BufNewFile,BufRead *.tex syn match texMathSymbol '\\rangle\>' contained conceal cchar=⟩
augroup END
set conceallevel=2
set background=dark
set termguicolors
let g:tokyonight_style = 'storm'
colo tokyonight
augroup colorschemeConceal
  autocmd!
  au Colorscheme * hi! link Conceal Normal
augroup END
let g:html_indent_inctags="head,html,body,p,head,table,tbody,div,script"
let g:html_indent_script1="inc"
let g:html_indent_style1="inc"
" General shortcuts {{{1
nnoremap <leader>ev :sp $MYVIMRC<cr>
nnoremap <silent> <leader>sv :so $MYVIMRC<cr>
" quickly switch between alternate buffers
nnoremap <leader>; :e #<cr>
" Easy folding toggle with Space
nnoremap <Space> za
set pastetoggle=<F2>
noremap Q gq
" allows incsearch highlighting for range commands
cnoremap $t <CR>:t''<CR>
cnoremap $T <CR>:T''<CR>
cnoremap $m <CR>:m''<CR>
cnoremap $M <CR>:M''<CR>
cnoremap $d <CR>:d<CR>``
set viewoptions-=options
" Plugin Shortcuts and Configuration {{{1
" netrw {{{2
nnoremap <silent> <Leader>nt :Explore<CR>
" UltiSnips {{{2
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
" }}}
" airline {{{2
let g:airline_theme='tokyonight'
set noshowmode
" }}}
" Tab ignore and number column width {{{
" When doing tab completion, give the following files lower priority. You may
" wish to set 'wildignore' to completely ignore files, and 'wildmenu' to enable
" enhanced tab completion. These can be done in the user vimrc file.
set suffixes+=.info,.aux,.log,.dvi,.bbl,.out,.o,.lo
set wildignore=*.info,*.aux,*.log,*.dvi,*.bbl,*.out,*.o,*.lo,*.blg,*.pdf,*.pdfsync,*.bcf,*.gz,*.fdb_latexmk,*.fls

" When displaying line numbers, don't use an annoyingly wide number column. This
" doesn't enable line numbers -- :set number will do that. The value given is a
" minimum width to use for the number column, not a fixed size.
if v:version >= 700
  set numberwidth=3
endif
